### ISSUE TITLE
`g<C-A>` not working

### ISSUE THREAD

**Issue by oncomouse** [monaqa/dial.nvim#73] opened 2023-08-21 14:57 UTC
It seems `g<C-A>` is not working. If I select the ones in the example below using visual block mode and press `g<C-A>`, nothing happens:

~~~
1.
1.
1.
1.
1.
~~~

If I run `:vunmap g<C-A>` and reselect the same area in visual block mode, pressing `g<C-A>` yields the following result:

~~~
2.
3.
4.
5.
6.
~~~

Not sure what's causing this. I'm using the following spec with [lazy.nvim](https://github.com/folke/lazy.nvim) to load dial.nvim, if that matters:

~~~lua
return {
  "monaqa/dial.nvim",
  keys = {
    { "<C-a>", "<Plug>(dial-increment)", mode = { "n", "v" } },
    { "<C-x>", "<Plug>(dial-decrement)", mode = { "n", "v" } },
    { "g<C-a>", "g<Plug>(dial-increment)", mode = { "n", "v" } },
    { "g<C-x>", "g<Plug>(dial-decrement)", mode = { "n", "v" } },
  },
  config = function()
    local augend = require("dial.augend")
    require("dial.config").augends:register_group({
      -- default augends used when no group name is specified
      default = {
        augend.integer.alias.decimal, -- nonnegative decimal number (0, 1, 2, 3, ...)
        augend.integer.alias.hex, -- nonnegative hex number  (0x01, 0x1a1f, etc.)
        augend.constant.alias.bool, -- boolean value (true <-> false)
        augend.date.alias["%Y/%m/%d"], -- date (2022/02/18, etc.)
        augend.date.alias["%m/%d/%Y"], -- date (02/19/2022)
        -- augend.date.alias["%m-%d-%Y"], -- date (02-19-2022)
        -- augend.date.alias["%Y-%m-%d"], -- date (02-19-2022)
        augend.date.new({
          pattern = "%m.%d.%Y",
          default_kind = "day",
          only_valid = true,
          word = false,
        }),
        augend.misc.alias.markdown_header,
      },
    })
  end,
}
~~~

**Comment by monaqa** [comment] 2023-08-22 01:52
Hmm... it seems to be a bug. Thank you for your report.
The following configuration should work, so please use this style as a temporary measure.

```
keys = {
    {
        "g<C-a>",
        function()
            require("dial.map").manipulate("increment", "gnormal")
        end,
    },
    {
        "g<C-a>",
        function()
            require("dial.map").manipulate("increment", "gvisual")
        end,
        mode = "v",
    },
    ...
},
...
```

**Comment by oncomouse** [comment] 2023-08-23 15:07
Yes, the temporary fix you suggested does work. Thank you for getting me back working for now.

**Comment by monaqa** [comment] 2023-08-27 06:33
I thought it was a bug in dial.nvim, but it may be due to the Neovim spec (or bug?).
According to my local Neovim, while `<Plug>(dial-increment)` map expands recursively, `g<Plug>(dial-increment)` map does not.

Could you try the following setting?

```lua
    ...
    keys = {
        { "<C-a>", "<Plug>(dial-increment)", mode = { "n", "v" }},
        { "<C-x>", "<Plug>(dial-decrement)", mode = { "n", "v" }},
        { "g<C-a>", "g<Plug>(dial-increment)", mode = { "n", "v" }, remap = true },
        { "g<C-x>", "g<Plug>(dial-decrement)", mode = { "n", "v" }, remap = true },
    },
    ...
```

**Comment by oncomouse** [comment] 2023-08-29 18:54
Sorry it took me a bit to get back: adding `remap = true` does seem to solve the problem I was having.

**Comment by monaqa** [comment] 2023-09-09 03:20
I'm closing this issue because it seems I just misunderstood the specs and it is not a bug in dial.nvim or Neovim.

**Closed by monaqa** 2023-09-09 03:20 UTC
